version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: dummy
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: mypassword
    network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
